export const GET_ALL_TEXT = "GET_ALL_TEXT";
export const GET_ALL_TEXT_SUCCESS = "GET_ALL_TEXT_SUCCESS";
export const GET_ALL_TEXT_ERROR = "GET_ALL_TEXT_ERROR";

export const GET_ALL_IMAGES = "GET_ALL_IMAGES";
export const GET_ALL_IMAGES_SUCCESS = "GET_ALL_IMAGES_SUCCESS";
export const GET_ALL_IMAGES_ERROR = "GET_ALL_IMAGES_ERROR";

export const GET_SOCIAL_MEDIA = "GET_SOCIAL_MEDIA";
export const GET_SOCIAL_MEDIA_SUCCESS = "GET_SOCIAL_MEDIA_SUCESS";
export const GET_SOCIAL_MEDIA_ERROR = "GET_SOCIAL_MEDIA_ERROR";

export const GET_GITHUB_REPOS = "GET_GITHUB_REPOS";
export const GET_GITHUB_REPOS_SUCCESS = "GET_GITHUB_REPOS_SUCCESS";
export const GET_GITHUB_REPOS_ERROR = "GET_GITHUB_REPOS_ERROR";

export const GET_FILTERED_REPOS = "GET_FILTERED_REPOS";
export const GET_FILTERED_REPOS_SUCCESS = "GET_FILTERED_REPOS_SUCCESS";
export const GET_FILTERED_REPOS_ERROR = "GET_FILTERED_REPOS_ERROR";

export const GET_CAROUSEL = "GET_CAROUSEL"
export const GET_CAROUSEL_SUCCESS = "GET_CAROUSEL_SUCCESS"
export const GET_CAROUSEL_ERROR = "GET_CAROUSEL_ERROR"

export const GET_NAVBAR = "GET_NAVBAR"
export const GET_NAVBAR_SUCCESS = "GET_NAVBAR_SUCCESS"
export const GET_NAVBAR_ERROR = "GET_NAVBAR_ERROR"

export const GET_CONFIGURATION = "GET_CONFIGURATION"
export const GET_CONFIGURATION_SUCCESS = "GET_CONFIGURATION_SUCCESS"
export const GET_CONFIGURATION_ERROR = "GET_CONFIGURATION_ERROR"